name: GHAS Analysis Old To be Replaced

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  analyze:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        language: [ 'go' ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: ${{ matrix.language }}

      - name: Build and analyze with CodeQL
        uses: github/codeql-action/analyze@v1

      - name: Upload SARIF results
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: ${{ github.workspace }}/codeql-sarif-results.sarif
  dependencyCheck:
    name: Dependency Checkout
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix: 
        language: [ 'java' ]

    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: GK Dependency Checkout
        run: mvn dependency-check:check
        continue-on-error: true

      # Upload the SARIF results
      - name: Upload SARIF results
        uses: github/codeql-action/upload-sarif@v1
        continue-on-error: true
        with:
          sarif_file: target/dependency-check-report.sarfi

      - name: Upload Gk dependency scan report
        if : always()
        uses: actions/upload-artifact@v1
        continue-on-error: true
        with:
          name: gk-dependency-check-report
          path: ${{ github.workspace }}/target/dependency-check-report.html