name: Replace Strings

on:
  push:
    branches:
      - github-migration

jobs:
  replace-strings:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install openpyxl

      - name: Replace Strings in YML files
        run: |
          python script/string-replaces.py
        env:
          EXCEL_FILE: "files/File-Replacement.xlsx"
          GITHUB_WORKSPACE: ${{ github.workspace }}
        shell: bash
